// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK4Bw3fQpJGlt5kqDJvz8w-xQdZZLQO2M',
    appId: '1:827033380382:web:fa26f915847d837f5e300f',
    messagingSenderId: '827033380382',
    projectId: 'bantay-ulang',
    authDomain: 'bantay-ulang.firebaseapp.com',
    storageBucket: 'bantay-ulang.firebasestorage.app',
    measurementId: 'G-1DVHW69G6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz9q6lml9muXd6zCtgdrL8-rLtDFWm14E',
    appId: '1:827033380382:android:f5ac08f92209c0e15e300f',
    messagingSenderId: '827033380382',
    projectId: 'bantay-ulang',
    storageBucket: 'bantay-ulang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmbcFgytGxN9JD25Sud92MoEPupl7ZeUI',
    appId: '1:827033380382:ios:7f4086a463b712ec5e300f',
    messagingSenderId: '827033380382',
    projectId: 'bantay-ulang',
    storageBucket: 'bantay-ulang.firebasestorage.app',
    iosClientId: '827033380382-v298vgfi15hh46gtrvmo3j1ja67nm95e.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo1Langto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmbcFgytGxN9JD25Sud92MoEPupl7ZeUI',
    appId: '1:827033380382:ios:7f4086a463b712ec5e300f',
    messagingSenderId: '827033380382',
    projectId: 'bantay-ulang',
    storageBucket: 'bantay-ulang.firebasestorage.app',
    iosClientId: '827033380382-v298vgfi15hh46gtrvmo3j1ja67nm95e.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo1Langto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK4Bw3fQpJGlt5kqDJvz8w-xQdZZLQO2M',
    appId: '1:827033380382:web:96e03632e992ea185e300f',
    messagingSenderId: '827033380382',
    projectId: 'bantay-ulang',
    authDomain: 'bantay-ulang.firebaseapp.com',
    storageBucket: 'bantay-ulang.firebasestorage.app',
    measurementId: 'G-QW7T65LHJW',
  );
}
