import { db } from "./firebase.js";
import {
    collection,
    query,
    orderBy,
    limit,
    onSnapshot
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

/*
 * Firestore — sensor_readings collection
 *
 * Each document is created by the ESP32 on every measurement cycle.
 * Document ID: auto-generated by Firestore (addDoc).
 *
 * Schema:
 *   phLevel         : number    – pH level (e.g. 7.2, range 0–14)
 *   waterTemp       : number    – Water temperature in °C
 *   dissolvedOxygen : number    – Dissolved oxygen in mg/L
 *   waterLevel      : number    – Water level in meters (e.g. 1.50)
 *   salinity        : number    – Salinity in parts per thousand (ppt)
 *   turbidity       : number    – Turbidity in NTU
 *   timestamp       : timestamp – Firestore server timestamp (set by ESP32 via serverTimestamp())
 *   deviceId        : string    – ESP32 device identifier, e.g. "ESP32-001"
 *   status          : string    – Overall reading classification: "normal" | "warning" | "critical"
 *
 * Example document written by the ESP32:
 * {
 *   phLevel: 7.2,
 *   waterTemp: 24.5,
 *   dissolvedOxygen: 6.8,
 *   waterLevel: 1.50,
 *   salinity: 15,
 *   turbidity: 3.5,
 *   timestamp: <serverTimestamp>,
 *   deviceId: "ESP32-001",
 *   status: "normal"
 * }
 */

const SENSOR_MAP = [
    { key: "phLevel",         selector: '[data-sensor="ph"]',           unit: "",      decimals: 1 },
    { key: "dissolvedOxygen", selector: '[data-sensor="do"]',           unit: " mg/L", decimals: 1 },
    { key: "waterTemp",       selector: '[data-sensor="temp"]',         unit: "°C",    decimals: 1 },
    { key: "salinity",        selector: '[data-sensor="salinity"]',     unit: " ppt",  decimals: 0 },
    { key: "turbidity",       selector: '[data-sensor="turbidity"]',    unit: " NTU",  decimals: 1 },
    { key: "waterLevel",      selector: '[data-sensor="water-level"]',  unit: " m",    decimals: 2 }
];

const STATUS_CSS   = { normal: "optimal",  warning: "warning",  critical: "critical" };
const STATUS_LABEL = { normal: "OPTIMAL",  warning: "WARNING",  critical: "CRITICAL" };

// Safe ranges per parameter key — mirrors alertsEngine.js SAFE_RANGES
const SAFE_RANGES = {
    phLevel:         { min: 6.5,  max: 8.5  },
    waterTemp:       { min: 22,   max: 32   },
    dissolvedOxygen: { min: 5,    max: null },
    salinity:        { min: 0,    max: 5    },
    turbidity:       { min: null, max: 25   },
    waterLevel:      { min: 0.5,  max: 2.0  }
};

function getSensorStatus(key, value) {
    const range = SAFE_RANGES[key];
    if (!range || value == null || !Number.isFinite(Number(value))) return "normal";
    const v = Number(value);
    const { min, max } = range;
    const hasMin = min != null;
    const hasMax = max != null;

    const belowMin = hasMin && v < min;
    const aboveMax = hasMax && v > max;
    if (!belowMin && !aboveMax) return "normal";

    let ratio;
    if (hasMin && hasMax) {
        const rangeSize = max - min;
        ratio = belowMin ? (min - v) / rangeSize : (v - max) / rangeSize;
    } else if (hasMin) {
        // One-sided min (e.g. DO > 5): ratio relative to the minimum threshold
        ratio = (min - v) / min;
    } else {
        // One-sided max (e.g. turbidity < 25): ratio relative to the max threshold
        ratio = (v - max) / max;
    }

    return ratio <= 0.10 ? "warning" : "critical";
}

function formatValue(value, decimals, unit) {
    const n = Number(value);
    if (value == null || !Number.isFinite(n)) return "--";
    return (decimals === 0 ? Math.round(n) : n.toFixed(decimals)) + unit;
}

const VALUE_COLOR = { optimal: "#2563eb", warning: "#d97706", critical: "#dc2626" };

function applyCardStatus(card, status) {
    const statusEl = card.querySelector(".sensor-status");
    const iconWrap = card.querySelector(".sensor-icon-wrap");
    const valueEl  = card.querySelector(".sensor-value");
    const css      = STATUS_CSS[status]   || "optimal";
    const label    = STATUS_LABEL[status] || "OPTIMAL";

    ["optimal", "warning", "critical"].forEach(c => {
        if (statusEl) statusEl.classList.toggle(c, c === css);
        if (iconWrap) iconWrap.classList.toggle(c, c === css);
    });
    if (statusEl) statusEl.textContent = label;
    if (valueEl)  valueEl.style.color  = VALUE_COLOR[css];
}

function updateSensorCards(data) {
    const sensorGrid = document.getElementById("sensorGrid");
    if (!sensorGrid) return;

    const timeStr = new Date().toLocaleTimeString("en-PH", { hour: "2-digit", minute: "2-digit" });

    SENSOR_MAP.forEach(({ key, selector, unit, decimals }) => {
        const card = sensorGrid.querySelector(selector);
        if (!card) return;

        const valueEl   = card.querySelector(".sensor-value");
        const updatedEl = card.querySelector(".sensor-updated");

        if (valueEl)   valueEl.textContent = formatValue(data[key], decimals, unit);
        if (updatedEl) updatedEl.textContent = "Updated: " + timeStr;

        applyCardStatus(card, getSensorStatus(key, data[key]));
    });
}

/**
 * receiveSensorData()
 *
 * Opens a real-time Firestore listener on the sensor_readings collection.
 * Every time the ESP32 writes a new document, the listener fires, updates
 * every sensor card on the page, and broadcasts a "sensor-reading-updated"
 * CustomEvent so other modules (charts, alerts, etc.) can react.
 *
 * Sets window.sensorDataConnected = true on first successful read so the
 * simulation in real-time-monitoring.js knows to stop overwriting values.
 *
 * Returns the Firestore unsubscribe function — call it to stop listening.
 */
export function receiveSensorData() {
    const q = query(
        collection(db, "sensor_readings"),
        orderBy("timestamp", "desc"),
        limit(1)
    );

    const unsubscribe = onSnapshot(
        q,
        (snapshot) => {
            if (snapshot.empty) return;

            // Permanently kill both simulation intervals (tick + runClock)
            if (typeof window.stopSensorSimulation === "function") {
                window.stopSensorSimulation();
                window.stopSensorSimulation = null;
            }

            const data = snapshot.docs[0].data();

            updateSensorCards(data);

            // Make the latest reading globally accessible
            window.latestSensorReading = data;
            window.sensorDataConnected = true;

            // Broadcast so the dashboard, charts, or alerts can react
            document.dispatchEvent(
                new CustomEvent("sensor-reading-updated", { detail: data })
            );
        },
        (error) => {
            console.error("sensor_readings listener error:", error);
        }
    );

    return unsubscribe;
}
